countdown/index.html

- Fix for multiple browsers
- Linting
- Use correct date for 2015

Fix countdown page

---

_layouts/responsive.html
css/bootstrap.css
index.html

a couple changes to the home page to make it a bit cleaner. feel free to cherry pick changes.

some ui changes

---

_data/sponsors.yml

blurb given in a mail a couple days back

update oracle text on website

---

_data/sponsors.yml

Since being established in 2001, RSAWEB has grown rapidly, gaining extensive industry experience while continuously improving on, and introducing new products including our latest offerings; <a href="http://www.rsaweb.co.za/hosting/flex-cloud/">Flex Cloud</a> and <a href="http://www.rsaweb.co.za/connectivity/fibre/">City Fibre</a>. With great commitment to customer service excellence and in-depth technical understanding, RSAWEB is able to retain partnerships with some of South Africa’s leading brands, from a wide array of sectors. RSAWEB takes pride in offering custom made solutions to clients as well as the best in service and support, providing Service-Level Agreements and a 24-hour helpdesk that fully supports and monitors all services, ensuring all clients have absolute peace of mind. …

Update RSAWEB copy

---

.gitignore
Gemfile

https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll
For easier local dev.

Create a gemfile for github-pages

---

sponsors/index.html

Fixes https://github.com/scaleconf/scaleconf.github.com/issues/159

Comment out sponsors and add a paragraph about sponsoring

---

purchase/index.html

Fixes https://github.com/scaleconf/scaleconf.github.com/issues/158
I wasn't sure what to do about Duncan's comment, so I just commented out that block because payments aren't open currently. 
Shout if I should change that.

Change dates for 2016 to TBD and comment out payment help

---

schedule/index.html

Fixes https://github.com/scaleconf/scaleconf.github.com/issues/157

Replace schedule with text about the upcoming schedule

---

_layouts/responsive.html
codeofconduct/index.html

We said http://confcodeofconduct.com/

Add code of conduct to site

---

about/index.html
purchase/index.html
schedule/index.html
speak/index.html
videos/index.html

It may return if we feel like it, or in 2017

Drop biz day for 2016

---

_data/schedule.yml
index.html
sponsors/index.html
sponsors/packages.html

Add dates and sponsorship for 2016

---

index.html

Because we’re now in *this* year.

Change "next" to "this"

---

_data/sponsors.yml
sponsors/index.html

add sponsors onto sponsors page
#175

add takealot, google, oracle, rsaweb to sponsors

---

_layouts/responsive.html
index.html
purchase/index.html
speak/index.html
sponsors/index.html

Not 100% sure if this is all correct.

Make tickets for 2016 available

---

_data/speakers.yml
_layouts/speaker-info.html

A technical conference without github links? This is madness!
I'll backfill a few after this PR lands.

Add 'Follow on github' link to speakers

---

_data/speakers.yml

Add a few github profiles

---

_data/speakers.yml

Remove talk title/abstract from bio field, and update abstract to intended content.

Fix mgorven bio

---

sponsors/index.html

For https://github.com/scaleconf/scaleconf.github.com/issues/194.

Fix the sponsor logos

---

_config.yml

Fixes https://github.com/scaleconf/scaleconf.github.com/issues/190

Remove highlighter and markdown settings

---

_data/sponsors.yml

Update OfferZen URL

---

_data/speakers.yml

Update Michael's stuff

---

_config.yml
_data/config.yml
_layouts/responsive.html
index.html
purchase/index.html

This doesn't turn off the quicket iframe

Option to turn ticket sales off/on and waiting list on/off

---

_data/speakers.yml

unnecessary space in framework

fixed spelling error

---

_data/config.yml

Surely it's time to turn ticket sales proper off?

Turn ticket sales off

---

_layouts/sponsor-info.html
sponsors/offerzen.html

I can't seem to find a use for the sponsor's website attribute.

Link to sponsor image to sponsor website

---

_layouts/responsive.html

fixes https://github.com/scaleconf/scaleconf.github.com/issues/220
Is lanyrd even useful?

Kill lanyrd

---

_data/config.yml
index.html

Basically wrapped what https://github.com/scaleconf/scaleconf.github.com/pull/230 does into some if statements.
This PR is into https://github.com/scaleconf/scaleconf.github.com/pull/230 BTW.

Try add a in_planning mode to the site

---

_data/config.yml
purchase/index.html

https://github.com/scaleconf/scaleconf.github.com/issues/223
I'm not sure how I feel about the `conf_being_organised` variable. Couldn't think of anything better.

Update purchase page post scaleconf 2016

---

_data/speakers.yml

Still waiting on edited videos for Michael Gorven and Len Wencier. Marnus says he can do them next week.
@vhata can you make the video’s public to the whole world? Then this guy can be merged and we can tweet.

2015 & 2016 videos

---

_data/speakers.yml

Ref - https://twitter.com/scaleconf/status/798268918867456000

Fix the video link for bridgetkromhout's talk

---

_data/config.yml
_includes/quicket-frame.html
_layouts/base.html
index.html
purchase/index.html

I can't test the iframe because tickets not active, so pretend the woo is replaced with the quicket widget

purchase page for tickets

---

_data/config.yml
_data/speakers.yml
_layouts/base.html
index.html

remove submit, move confirmed speakers above buy tickets

---

_data/speakers.yml

Remove extra quotes

---

_data/config.yml
_layouts/base.html
index.html

waiting list section and config

---

_data/config.yml
_data/speakers.yml
index.html
purchase/index.html
speakers/2018.html
submit-talk/index.html

a little bit wonky because i zoomed out, but screenshot below

reset site for 2018

---

about/index.html
submit-talk/index.html

https://github.com/scaleconf/scaleconf.github.com/issues/278
and
https://github.com/scaleconf/scaleconf.github.com/issues/279

Use papercall.io

---

_data/schedule.yml
_data/sponsors.yml
_layouts/base.html
index.html
sponsors/index.html

A note - I changed /sponsor with text at the top inviting more sponsors to contact us - in case people think we the 4 sponsors listed are the only ones. My words aren't great at the moment, so if you want different text, let me know?

First 2018 updates

---

_data/sponsors.yml

Add Impact Radius

---

_data/config.yml
_data/speakers.yml
index.html

To merge once we're sold out which is in 10 tickets time.

Waiting list + speaker updates

---

_data/speakers.yml

He was still on the speaker list/page

remove michael

---

_data/speakers.yml

An updated video with a couple edits

new video id for Andrew

---

_data/config.yml
_data/speakers.yml
submit-talk/index.html

* Add 2019 dates
* Change the site to accept talks

Add 2019 CFP

---

_data/sponsors.yml

Tweak Takealot's text

---

_data/sponsors.yml

* Add Allan Gray as sponsor
* Update the sponsor blurb

Add Allan Gray

---

_data/speakers.yml

https://github.com/scaleconf/scaleconf.github.com/pull/330

Remove Oliver

---

_data/schedule.yml
_includes/schedule.html

Dale Humby mailed because https://scaleconf.org/schedule/ is the first link on Googs. We should have TBC in the meantime. Or you can do something else, I don't mind...

TBC schedule

---

_data/sponsors.yml

Just adds some contact details at the bottom.

Update Equal Experts

---

_data/schedule.yml

* Oops, Dale's first talk by mistake
* Tweaks to the schedule

Wrong talk for Dale

---

_data/speakers.yml

She wanted to change some of the wording.

Update Grace's talk

---

_data/schedule.yml

Switch break info

---

_data/speakers.yml

Because "someone didn't give it to you".

Tim's twitter

---

_data/config.yml
_data/speakers.yml

* Making ScaleConf 2019 in the past
* Randomly leave 6 speakers on the home page

Post conf updates

---

_data/speakers.yml
about/index.html

* Adds 2019 videos to /speakers
* Removes JSinSA as a conference, it looks like it doesn't happen anymore

Add 2019 videos

---

_data/config.yml
purchase/index.html
submit-talk/index.html

* Adds 2020 dates
* Opens CFP
* Remove Lessfuss reference because we're now ScaleConf (Pty) Ltd

Add 2020 dates and CFP

---

submit-talk/index.html

Who knew there was a second button on the page?

There's a 2nd Papercall URL

---

_data/sponsors.yml
index.html
sponsors/index.html

Premier sponsors: Elastic and Luno

Adds first confirmed sponsors

---

_layouts/speakers-by-year.html
submit-talk/index.html

Adding the deadline date on /submit-talk and some text tweaks

Add CFP deadline

---

_data/config.yml
_data/schedule.yml
_includes/quicket-frame.html
_includes/schedule.html
about/index.html
index.html
purchase/success.html

* Add Quicket code/widget and success page
* Update the waiting list form URL
* Update the site to have a blank 2020 schedule page (it's hidden)
* Update info on some of the other confs

Getting ready for ticket sales

---

_layouts/speakers-by-year.html
speakers/2020.html

Also only display the CFP link if it's actually open

Fix 404 on /speakers/2020

---

_data/sponsors.yml

Can we centre the bottom logo? Or is it ok as is?

Add Google

---

_data/config.yml
_data/speakers.yml
about/index.html

Random selection of past speakers on the home page, feel free to change them...

Post conf update

---

_data/team.yml
_layouts/base.html
css/scaleconf.css
index.html

We have decided not to continue putting ScaleConf on.  This is our farewell message.
Preview:

Farewell message
